### ISSUE TITLE
miniupnpc not found

### ISSUE THREAD

**Issue by fromjonathan** [Astrumcash/astrum#4]
when running make -f makefile.unix # Headless
it ends with this error:

fatal error: miniupnpc/miniupnpc.h: No such file or directory
 #include <miniupnpc/miniupnpc.h>
                                 ^
compilation terminated.
make: *** [obj/net.o] Error 1

**Comment by minerric** [comment]
try installing it using this 

sudo apt-get install libminiupnpc-dev
